M48
; DRILL file {KiCad 8.0.6} date 2025-02-23T17:02:58-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-23T17:02:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.3307
%
G90
G05
T1
X2.9606Y-2.9606
X2.9606Y-4.9134
X4.9134Y-2.9606
X4.9134Y-4.9134
T2
X3.937Y-3.937
M30
